### PR TITLE
Add minutes for 2019-09-03

### PR DESCRIPTION
**Pull request by sedders123**

### CODE REVIEW

**Comment by antoinepetty** [comment]
Perhaps mention the action to advertise entries being open. (Even though this was completed after the call, before this will be merged)

**Comment by RealOrangeOne** [comment]
I agree with @antoinepetty. We never really formally closed the meeting, so the decisions after it are definitely worth noting down.

Incidentally, they're also covered by https://github.com/srobo/tasks/issues/308 and https://github.com/srobo/tasks/issues/307

**Comment by sedders123** [comment]
If I remember correctly I stopped minuting when Andy BS left us and we said it was now a 'doing'. Unfortunately, I can't really remember what was discussed in the doing. If we can remember I'm happy to add it, but as it has been a couple of weeks may just be worth merging these.

**Comment by antoinepetty** [comment]
@sedders123 Happy to merge now

**Pull request merged**
